[package]
name = "override-competition"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ozton = { path = "../ozton/packages/ozton", version = "0.4.0" }
vexide = { version = "=0.9.0-alpha.1", features = ["full", "default-sdk"] }

[package.metadata.v5]
upload-strategy = "differential"
slot = 1
compress = true

[profile.release]
opt-level = 3
lto = "fat"
